name: Deploy to Production

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 109.196.100.134
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Переходим в директорию проекта
            cd /var/www/zahalal-main || mkdir -p /var/www/zahalal-main

            # Останавливаем текущий процесс если он запущен
            pm2 stop zahalal-app || true
            pm2 delete zahalal-app || true

            # Клонируем или обновляем репозиторий
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/${{ github.repository }}.git .
            fi

            # Устанавливаем зависимости
            npm ci --production
            npm i
            # Собираем проект
            npm run build

            # Запускаем приложение через PM2
            pm2 start npm --name "zahalal-app" -- start
            pm2 save
            pm2 startup

            # Проверяем статус
            pm2 status